name: André Felipe
favicon: null
layout_spectrum: 0.04734940989874303
typography_spectrum: 0.3717585923150182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.99872234207578
  lightness: 0.6824373281560838
  saturation: 0.39645177219063044
  rhythmicContrast: 0.3127902364358306
purpose: []
